import json

# Part 1 generator (1 - 250)
def generate():
    raw_data = [
        # (id, topic, type, kana, kanji, han_viet, meaning, coll, syn, ant, nuance, ex_jp, ex_vn)
        (1, "Hành động, Trạng thái & Mức độ", "Phó từ (副詞)", "あいかわらず", "相変わらず", "Tương biến", "Vẫn, như thường lệ", ["相変わらず元気 (Vẫn khỏe)", "相変わらず忙しい (Vẫn bận như cũ)"], [{"word": "依然として", "reading": "いぜんとして", "note": "Vẫn như cũ (trang trọng hơn)"}], [{"word": "一変して", "reading": "いっぺんして", "meaning": "Thay đổi hoàn toàn"}], "Chỉ trạng thái không đổi so với quá khứ. Bẫy N2 đồng nghĩa 依然として.", "彼は相変わらず忙しいです。", "Anh ấy vẫn bận rộn như thường lệ."),
        (2, "Giao thông, Du lịch & Không gian", "Phó từ (副詞)", "あいついで", "相次いで", "Tương thứ", "Liên tiếp, nối tiếp nhau", ["事故が相次ぐ (Tai nạn liên tiếp)", "批判が相次ぐ (Chỉ trích liên tiếp)"], [{"word": "続々と", "reading": "ぞくぞくと", "note": "Liên tục dồn dập"}, {"word": "次々に", "reading": "つぎつぎに", "note": "Lần lượt"}], [{"word": "途絶えて", "reading": "とだえて", "meaning": "Bị gián đoạn"}], "Dùng khi nhiều sự việc cùng loại xảy ra liên tiếp trong thời gian ngắn (tai nạn, tin tức).", "事故が相次いで起こる。", "Tai nạn xảy ra liên tiếp."),
        (3, "Y tế, Sức khỏe & Thể thao", "Danh từ (名詞)", "あいて", "相手", "Tương thủ", "Đối phương, đối thủ, bạn cùng làm", ["話し相手 (Bạn tâm sự)", "結婚相手 (Đối tượng kết hôn)", "相手にする (Bận tâm, tiếp chuyện)"], [{"word": "対象", "reading": "たいしょう", "note": "Đối tượng"}], [{"word": "自分", "reading": "じぶん", "meaning": "Bản thân"}], "Đi với cụm 相手にする (đối phó, tiếp chuyện), 相手にされない (bị ngó lơ).", "試合の相手が強いです。", "Đối thủ của trận đấu rất mạnh."),
        (4, "Hành động, Trạng thái & Mức độ", "Danh từ (名詞)", "アイデア", "アイデア", "-", "Ý tưởng, sáng kiến", ["アイデアが浮かぶ (Nảy ra ý tưởng)", "アイデアを出し合う (Cùng đóng góp ý tưởng)"], [{"word": "着想", "reading": "ちゃくそう", "note": "Ý tưởng khởi xướng"}, {"word": "思いつき", "reading": "おもいつき", "note": "Ý nghĩ lóe lên"}], [], "Thường đi với động từ アイデアが浮かぶ (nảy ra ý tưởng mới).", "新しいアイデアが浮かびました。", "Một ý tưởng mới đã xuất hiện."),
        (5, "Kinh tế, Tài chính & Xã hội", "Phó từ (副詞)", "あいにく", "あいにく", "-", "Không may, đáng tiếc", ["あいにくの雨 (Trận mưa không đúng lúc)", "あいにく留守にする (Rất tiếc đúng lúc đi vắng)"], [{"word": "折悪しく", "reading": "おりあしく", "note": "Không may gặp lúc"}], [], "Bẫy N2 dùng khi từ chối lịch hẹn kèm sự tiếc nuối (あいにくですが...).", "あいにくですが、予約はいっぱいです。", "Rất tiếc, nhưng lịch hẹn đã đầy."),
        (6, "Con người, Tính cách & Cảm xúc", "Tính từ đuôi な (な形容詞)", "あいまい", "曖昧", "Ái muội", "Mập mờ, không rõ ràng", ["あいまいな返事 (Câu trả lời mập mờ)", "あいまいな態度 (Thái độ không rõ ràng)"], [{"word": "はっきりしない", "reading": "", "note": "Không rõ ràng"}], [{"word": "明確な", "reading": "めいかくな", "meaning": "Rõ ràng, minh bạch"}], "Bổ nghĩa danh từ dùng 'あいまいな＋N', phó từ 'あいまいに＋V'.", "彼の説明はあいまいです。", "Giải thích của anh ấy không rõ ràng."),
        (7, "Hành động, Trạng thái & Mức độ", "Động từ ghép (複合動詞)", "あう", "遭う", "Tao", "Gặp (tai nạn, chuyện xui)", ["事故に遭う (Gặp tai nạn)", "ひどい目に遭う (Gặp chuyện tồi tệ)", "災難に遭う (Gặp tai ương)"], [{"word": "出くわす", "reading": "でくわす", "note": "Bất ngờ chạm mặt"}], [], "Bắt buộc đi với trợ từ に và CHỈ DÙNG CHO SỰ CỐ, TAI NẠN, việc xấu.", "事故に遭いました。", "Tôi đã gặp tai nạn."),
        (8, "Hành động, Trạng thái & Mức độ", "Danh từ (名詞)", "あう", "合う", "Hợp", "Hợp, vừa vặn, khớp", ["気が合う (Hợp tính nhau)", "口に合う (Hợp khẩu vị)", "目と目が合う (Hai ánh mắt chạm nhau)"], [{"word": "一致する", "reading": "いっちする", "note": "Trùng khớp"}, {"word": "適する", "reading": "てきする", "note": "Thích hợp"}], [], "Dùng cho sự vừa vặn kích cỡ, hợp tính, hợp khẩu vị.", "私たちは気が合う。", "Chúng tôi rất hợp nhau."),
        (9, "Y tế, Sức khỏe & Thể thao", "Tính từ đuôi い (い形容詞)", "あおじろい", "青白い", "Thanh bạch", "Xanh xao, nhợt nhạt", ["青白い顔 (Khuôn mặt xanh xao)", "青白く光る (Sáng xanh le lói)"], [{"word": "青ざめた", "reading": "あおざめた", "note": "Tái mét"}], [{"word": "血色がいい", "reading": "けっしょくがいい", "meaning": "Hồng hào"}], "Da mặt xanh xao, tái mét do bệnh tật, mất ngủ hoặc quá sợ hãi.", "彼の顔が青白いです。", "Mặt anh ấy xanh xao."),
        (10, "Kinh tế, Tài chính & Xã hội", "Danh từ (名詞)", "あかじ", "赤字", "Xích tự", "Lỗ, thâm hụt ngân sách", ["赤字を出す (Bị thua lỗ)", "赤字に陥る (Rơi vào thâm hụt)", "赤字を補う (Bù đắp khoản lỗ)"], [{"word": "損失", "reading": "そんしつ", "note": "Tổn thất"}], [{"word": "黒字", "reading": "くろじ", "meaning": "Có lãi, thặng dư"}], "Thường đi kèm động từ 赤字を出す, 赤字に陥る, 赤字を埋める.", "会社は赤字です。", "Công ty đang lỗ.")
    ]
    print(f"Generated {len(raw_data)} items for test")

generate()
