# Generator for Batch 1 (Items 1 to 250)
import json

def get_items():
    # Format: [id, topic_num, word_type, kana, kanji, han_viet, meaning, coll_list, syn_list, ant_list, nuance, ex_jp, ex_vn]
    items = [
        [1, 1, "Phó từ", "あいかわらず", "相変わらず", "Tương biến", "Vẫn, như thường lệ", ["相変わらず元気 (Vẫn khỏe mạnh như mọi khi)", "相変わらず忙しい (Vẫn bận rộn như cũ)"], [{"word": "依然として", "reading": "いぜんとして", "note": "Vẫn như cũ"}], [{"word": "一変して", "reading": "いっぺんして", "meaning": "Thay đổi hoàn toàn"}], "Chỉ trạng thái không thay đổi so với quá khứ. Bẫy đồng nghĩa 依然として.", "彼は相変わらず忙しいです。", "Anh ấy vẫn bận rộn như thường lệ."],
        [2, 2, "Phó từ", "あいついで", "相次いで", "Tương thứ", "Liên tiếp, dồn dập", ["事故が相次ぐ (Tai nạn liên tiếp xảy ra)", "批判が相次ぐ (Hứng chịu chỉ trích liên tục)"], [{"word": "続々と", "reading": "ぞくぞくと", "note": "Liên tục"}, {"word": "次々に", "reading": "つぎつぎに", "note": "Lần lượt"}], [{"word": "途絶えて", "reading": "とだえて", "meaning": "Bị gián đoạn"}], "Chỉ các sự kiện cùng loại xảy ra liên tiếp trong thời gian ngắn (tai nạn, sự cố).", "事故が相次いで起こる。", "Tai nạn xảy ra liên tiếp."],
        [3, 3, "Danh từ", "あいて", "相手", "Tương thủ", "Đối phương, đối thủ", ["話し相手 (Bạn tâm sự)", "相手にする (Tiếp chuyện, đối phó)", "結婚相手 (Đối tượng kết hôn)"], [{"word": "対象", "reading": "たいしょう", "note": "Đối tượng"}], [{"word": "自分", "reading": "じぶん", "meaning": "Bản thân"}], "Cụm '相手にする' (bận tâm/tiếp chuyện) và '相手にされない' (bị ngó lơ).", "試合の相手が強いです。", "Đối thủ của trận đấu rất mạnh."],
        [4, 1, "Danh từ", "アイデア", "アイデア", "-", "Ý tưởng, sáng kiến", ["アイデアが浮かぶ (Nảy ra ý tưởng mới)", "アイデアを出し合う (Cùng đóng góp ý tưởng)"], [{"word": "着想", "reading": "ちゃくそう", "note": "Ý tưởng khởi đầu"}], [], "Thường đi với động từ アイデアが浮かぶ hoặc アイデアを出す.", "新しいアイデアが浮かびました。", "Một ý tưởng mới đã xuất hiện."],
        [5, 4, "Phó từ", "あいにく", "あいにく", "-", "Không may, đáng tiếc", ["あいにくの雨 (Trận mưa không đúng lúc)", "あいにく都合が悪い (Rất tiếc là bận không đi được)"], [{"word": "折悪しく", "reading": "おりあしく", "note": "Không may gặp lúc"}], [], "Luôn dùng khi từ chối lịch hẹn hoặc báo tin không thuận lợi kèm sự tiếc nuối.", "あいにくですが、予約はいっぱいです。", "Rất tiếc, nhưng lịch hẹn đã đầy."],
        [6, 5, "Tính từ", "あいまい", "曖昧", "Ái muội", "Mập mờ, không rõ ràng", ["あいまいな返事 (Câu trả lời mập mờ)", "あいまいな態度 (Thái độ không rõ ràng)"], [{"word": "はっきりしない", "reading": "", "note": "Không rõ ràng"}], [{"word": "明確な", "reading": "めいかくな", "meaning": "Minh bạch"}], "Bổ nghĩa cho danh từ dùng 'あいまいな＋N', bổ nghĩa động từ dùng 'あいまいに＋V'.", "彼の説明はあいまいです。", "Giải thích của anh ấy không rõ ràng."],
        [7, 1, "Động từ", "あう", "遭う", "Tao", "Gặp (tai nạn, xui xẻo)", ["事故に遭う (Gặp phải tai nạn)", "ひどい目に遭う (Gặp chuyện xui xẻo)"], [{"word": "出くわす", "reading": "でくわす", "note": "Bất ngờ chạm mặt"}], [], "Bắt buộc đi với trợ từ に và chỉ dùng cho việc xấu, tai họa.", "事故に遭いました。", "Tôi đã gặp tai nạn."],
        [8, 1, "Động từ", "あう", "合う", "Hợp", "Hợp, vừa vặn, khớp", ["気が合う (Hợp tính nhau)", "口に合う (Hợp khẩu vị)", "目と目が合う (Hai ánh mắt chạm nhau)"], [{"word": "一致する", "reading": "いっちする", "note": "Khớp"}], [], "Vừa vặn kích cỡ, hợp tính cách, hợp khẩu vị.", "私たちは気が合う。", "Chúng tôi rất hợp nhau."],
        [9, 3, "Tính từ", "あおじろい", "青白い", "Thanh bạch", "Xanh xao, nhợt nhạt", ["青白い顔 (Khuôn mặt xanh xao)", "青白く光る (Sáng xanh le lói)"], [{"word": "青ざめた", "reading": "あおざめた", "note": "Tái mét"}], [{"word": "血色がいい", "reading": "けっしょくがいい", "meaning": "Hồng hào"}], "Da mặt xanh xao, tái mét do bệnh tật, mất ngủ hoặc quá sợ hãi.", "彼の顔が青白いです。", "Mặt anh ấy xanh xao."],
        [10, 4, "Danh từ", "あかじ", "赤字", "Xích tự", "Lỗ, thâm hụt ngân sách", ["赤字を出す (Bị thua lỗ)", "赤字に陥る (Rơi vào thâm hụt)", "赤字を補う (Bù đắp khoản lỗ)"], [{"word": "損失", "reading": "そんしつ", "note": "Tổn thất"}], [{"word": "黒字", "reading": "くろじ", "meaning": "Có lãi, thặng dư"}], "Thường đi với 赤字を出す, 赤字に陥る, 赤字を埋める.", "会社は赤字です。", "Công ty đang lỗ."],
        [11, 5, "Động từ", "あがる", "上がる", "Thượng", "Căng thẳng, hồi hộp, hoàn thành", ["緊張で上がる (Căng thẳng cuống cuồng)", "原稿が上がる (Bản thảo đã hoàn thành)", "気温が上がる (Nhiệt độ tăng lên)"], [{"word": "緊張する", "reading": "きんちょうする", "note": "Căng thẳng"}], [{"word": "落ち着く", "reading": "おちつく", "meaning": "Bình tĩnh"}], "Bẫy N2: Ngoài nghĩa tăng lên, hay lừa nghĩa căng thẳng trước đám đông hoặc hoàn thành bản thảo.", "試験の前に緊張して上がる。", "Tôi căng thẳng trước kỳ thi."],
        [12, 7, "Động từ", "あがる", "上がる", "Thượng", "Hoàn thành, xong xuôi", ["宿題が上がる (Bài tập xong)", "料理が上がる (Món ăn nấu xong)"], [{"word": "完成する", "reading": "かんせいする", "note": "Hoàn thành"}], [], "Chỉ hành động hoàn thành, kết thúc một công việc.", "宿題が上がりました。", "Bài tập đã hoàn thành."],
        [13, 6, "Danh từ", "あきっぽい", "飽きっぽい", "Bão", "Dễ chán, cả thèm chóng chán", ["飽きっぽい性格 (Tính cả thèm chóng chán)", "飽きっぽくて続かない (Mau chán không duy trì được)"], [{"word": "移り気な", "reading": "うつりぎな", "note": "Hay thay đổi"}], [{"word": "根気強い", "reading": "こんきづよい", "meaning": "Kiên trì"}], "Hậu tố '～っぽい' mang nghĩa có xu hướng/dễ bị (hay tiêu cực).", "彼は飽きっぽい性格です。", "Anh ấy có tính dễ chán."],
        [14, 1, "Động từ", "あきらめる", "諦める", "Đế", "Từ bỏ, bỏ cuộc", ["夢を諦める (Từ bỏ ước mơ)", "途中で諦める (Bỏ cuộc giữa chừng)"], [{"word": "断念する", "reading": "だんねんする", "note": "Từ bỏ (văn viết)"}, {"word": "思い切る", "reading": "おもいきる", "note": "Dứt khoát từ bỏ"}], [{"word": "粘る", "reading": "ねばる", "meaning": "Kiên trì bám trụ"}], "Đồng nghĩa với 断念する trong văn bản trang trọng.", "夢を諦めないでください。", "Đừng từ bỏ giấc mơ của bạn."],
        [15, 6, "Động từ", "あきる", "飽きる", "Bão", "Chán ngấy, phát ngán", ["食べ飽きる (Ăn mãi phát ngấy)", "聞き飽きる (Nghe mãi mòn tai)"], [{"word": "うんざりする", "reading": "", "note": "Ngấy đến tận cổ"}], [{"word": "熱中する", "reading": "ねっちゅうする", "meaning": "Say mê"}], "Mất hết hứng thú vì lặp đi lặp lại một việc quá nhiều lần.", "彼はすぐに飽きる。", "Anh ấy dễ chán."],
        [16, 10, "Động từ", "あきれる", "呆れる", "Ngốc", "Sốc, ngán ngẩm, cạn lời", ["呆れて物も言えない (Cạn lời ngán ngẩm)", "無責任さに呆れる (Sốc trước sự vô trách nhiệm)"], [{"word": "開いた口がふさがらない", "reading": "", "note": "Há hốc mồm kinh ngạc"}], [{"word": "感心する", "reading": "かんしんする", "meaning": "Thán phục"}], "Luôn mang hàm ý tiêu cực (ngao ngán trước sự vô lý của người khác). Không dùng cho khen ngợi.", "彼の無責任さに呆れた。", "Tôi sốc vì sự vô trách nhiệm của anh ấy."],
        [17, 3, "Danh từ", "わる〜", "悪〜", "Ác", "Tiền tố: ~ xấu, tệ hại", ["悪天候 (Thời tiết xấu)", "悪循環 (Vòng luẩn quẩn)", "悪影響 (Ảnh hưởng tiêu cực)"], [], [{"word": "好〜", "reading": "こう", "meaning": "Tốt"}], "Tiền tố để chỉ điều xấu, không tốt liên quan đến từ đứng sau.", "悪天候のため、試合が中止された。", "Do thời tiết xấu, trận đấu đã bị hủy."],
        [18, 5, "Danh từ", "あくしゅ", "握手", "Ác thủ", "Bắt tay", ["固い握手を交わす (Bắt tay thật chặt)", "笑顔で握手する (Bắt tay mỉm cười thân thiện)"], [{"word": "手を握り合う", "reading": "", "note": "Nắm tay nhau"}], [], "Nghi thức bắt tay chào hỏi ngoại giao hoặc giảng hòa, hợp tác.", "彼と握手しました。", "Tôi đã bắt tay với anh ấy."],
        [19, 8, "Danh từ", "あくび", "あくび", "-", "Ngáp", ["大きなあくびをする (Ngáp lớn)", "あくびをかみ殺す (Nhịn ngáp)"], [], [], "Hành động mở miệng hít sâu khi buồn ngủ hoặc mệt mỏi.", "彼は大きなあくびをした。", "Anh ấy đã ngáp lớn."],
        [20, 2, "Phó từ", "あくまで", "あくまで", "-", "Đến cùng, chẳng qua chỉ là", ["あくまで主張する (Khăng khăng khẳng định đến cùng)", "あくまでも～にすぎない (Chẳng qua chỉ là...)"], [{"word": "徹底的に", "reading": "てっていてきに", "note": "Triệt để"}], [{"word": "妥協して", "reading": "だきょうして", "meaning": "Thỏa hiệp"}], "Hay đi kèm '～にすぎない' hoặc 'あくまでも～するつもりだ'.", "あくまでやり続けます。", "Tôi sẽ tiếp tục làm đến cùng."],
        [21, 1, "Danh từ", "〜あけ", "〜明け", "Minh", "Hậu tố: Vừa hết ~, sang ~", ["休み明け (Ngay sau kỳ nghỉ)", "梅雨明け (Hết mùa mưa)", "連休明け (Sau chuỗi ngày nghỉ)"], [{"word": "～終わり", "reading": "", "note": "Kết thúc"}], [{"word": "～入り", "reading": "", "meaning": "Bắt đầu vào"}], "Hậu tố chỉ thời điểm ngay sau khi kết thúc một khoảng thời gian.", "夜明けの空が美しい。", "Bầu trời lúc bình minh rất đẹp."],
        [22, 6, "Danh từ", "あけがた", "明け方", "Minh phương", "Lúc tảng sáng, rạng đông", ["明け方まで起きている (Thức trắng đến rạng đông)", "明け方の空 (Bầu trời lúc rạng sáng)"], [{"word": "夜明け", "reading": "よあけ", "note": "Rạng sáng"}], [{"word": "夕暮れ", "reading": "ゆうぐれ", "meaning": "Hoàng hôn"}], "Khoảng thời gian bầu trời hửng sáng trước khi mặt trời mọc.", "明け方まで働きました。", "Tôi đã làm việc đến lúc tảng sáng."],
        [23, 1, "Động từ", "あける", "明ける", "Minh", "Hết, kết thúc (đêm, năm, mùa mưa)", ["夜が明ける (Trời hửng sáng)", "年が明ける (Năm mới sang)", "梅雨が明ける (Hết mùa mưa)"], [{"word": "終わる", "reading": "おわる", "note": "Kết thúc"}], [{"word": "暮れる", "reading": "くれる", "meaning": "Lặn, tối"}], "Thường chỉ dùng với chủ ngữ cố định: 夜, 年, 梅雨.", "夜が明けた。", "Đêm đã tàn."],
        [24, 8, "Động từ", "あげる", "揚げる", "Dương", "Rán, chiên ngập dầu", ["鶏肉を揚げる (Rán ngập dầu thịt gà)", "旗を揚げる (Kéo cờ lên cao)"], [{"word": "フライにする", "reading": "", "note": "Chiên rán"}], [], "Làm chín thực phẩm ngập trong chảo dầu sôi (khác 炒める là xào ít dầu).", "鶏肉を揚げる。", "Rán gà."],
        [25, 2, "Động từ", "あげる", "上げる", "Thượng", "Nâng lên, đưa lên", ["荷物を上げる (Nâng hành lý lên)", "手を上げる (Giơ tay lên)"], [{"word": "持ち上げる", "reading": "もちあげる", "note": "Nhấc lên"}], [{"word": "下げる", "reading": "さげる", "meaning": "Hạ xuống"}], "Tha động từ: tác động nâng vật lên cao.", "荷物を上げる。", "Nâng hành lý lên."],
        [26, 5, "Động từ", "あこがれる", "憧れる", "Sung", "Ngưỡng mộ, khao khát", ["都会の生活に憧れる (Mơ ước cuộc sống thành thị)", "先輩に憧れる (Ngưỡng mộ tiền bối)"], [{"word": "羨望する", "reading": "せんぼうする", "note": "Ao ước ghen tị"}], [{"word": "幻滅する", "reading": "げんめつする", "meaning": "Vỡ mộng"}], "Luôn đi với trợ từ に (都会の生活に憧れる, 先輩に憧れる).", "彼に憧れています。", "Tôi ngưỡng mộ anh ấy."],
        [27, 8, "Danh từ", "あじつけ", "味付け", "Vị phó", "Nêm gia vị, nêm nếm", ["味付けが上手 (Nêm gia vị khéo)", "薄い味付け (Nêm vị thanh nhạt)"], [], [], "Dùng để chỉ việc nêm thêm gia vị vào món ăn trong nấu nướng.", "味付けが上手です。", "Việc nêm gia vị rất khéo léo."],
        [28, 8, "Động từ", "あじわう", "味わう", "Vị", "Thưởng thức, nếm trải", ["料理を味わう (Thưởng thức món ăn ngon)", "挫折を味わう (Nếm trải thất bại)", "苦しみを味わう (Nếm trải nỗi đau)"], [{"word": "堪能する", "reading": "たんのうする", "note": "Thưởng thức trọn vẹn"}], [], "Cảm nhận hương vị bằng vị giác hoặc nếm trải cảm xúc, nỗi đau.", "美味しい料理を味わう。", "Thưởng thức món ăn ngon."],
        [29, 2, "Quán dụng ngữ", "あしをのばす", "足を延ばす", "Túc duyên", "Tiện đường đi thêm, đi dấn", ["京都まで足を延ばす (Tiện đường đi thêm đến Kyoto)", "温泉に足を延ばす (Ghé thêm suối nước nóng)"], [{"word": "ついでに行く", "reading": "", "note": "Nhân tiện đi"}], [{"word": "引き返す", "reading": "ひきかえす", "meaning": "Quay trở lại"}], "Bẫy N2: Nghĩa là tiện đường đi thêm một đoạn xa hơn, không phải duỗi chân.", "温泉まで足を延ばしました。", "Tôi đã đi thêm đến suối nước nóng."],
        [30, 5, "Quán dụng ngữ", "あしをはこぶ", "足を運ぶ", "Túc vận", "Cất công đến tận nơi", ["何度も足を運ぶ (Nhiều lần cất công đến)", "劇場に足を運ぶ (Đích thân đến nhà hát)"], [{"word": "わざわざ行く", "reading": "", "note": "Cất công đi"}, {"word": "訪れる", "reading": "おとずれる", "note": "Ghé thăm"}], [], "Cất công đích thân đến nơi. Kính ngữ: ご足労いただく.", "遠くから足を運びました。", "Tôi đã cất công đến từ xa."],
        [31, 2, "Quán dụng ngữ", "あしをひっぱる", "足を引っ張る", "Túc dẫn", "Ngáng chân, thọc gậy bánh xe", ["チームの足を引っ張る (Làm vướng chân đồng đội)", "他人の足を引っ張る (Ngáng đường người khác)"], [{"word": "邪魔をする", "reading": "じゃまをする", "note": "Cản trở"}], [{"word": "後押しする", "reading": "あとおしする", "meaning": "Ủng hộ"}], "Nghĩa bóng là ngáng chân, làm cản trở tiến độ của tập thể.", "彼は他人の足を引っ張るのが好きです。", "Anh ấy thích ngáng chân người khác."],
        [32, 4, "Động từ", "あずける", "預ける", "Dự", "Gửi (tiền, đồ, con cái trông hộ)", ["荷物を預ける (Gửi hành lý)", "保育園に子供を預ける (Gửi con vào nhà trẻ)", "銀行にお金を預ける (Gửi tiết kiệm)"], [{"word": "委託する", "reading": "いたくする", "note": "Ủy thác"}], [{"word": "預かる", "reading": "あずかる", "meaning": "Nhận trông hộ"}, {"word": "引き取る", "reading": "ひきとる", "meaning": "Lấy lại"}], "預ける (mình gửi đồ cho người khác) <-> 預かる (mình nhận đồ trông hộ).", "子供を保育園に預けます。", "Tôi gửi con ở nhà trẻ."],
        [33, 3, "Danh từ", "あせ", "汗", "Hãn", "Mồ hôi", ["暑くて汗が出る (Nóng nên ra mồ hôi)", "汗を流す (Đổ mồ hôi công sức)"], [], [], "Mồ hôi tiết ra từ cơ thể khi lao động hoặc vận động.", "暑くて汗が出る。", "Nóng nên ra mồ hôi."],
        [34, 1, "Động từ", "あそびまわる", "遊び回る", "Du hồi", "Chơi lòng vòng, chơi khắp", ["公園を遊び回る (Chơi khắp công viên)"], [], [], "Đi chơi, khám phá nhiều nơi khác nhau.", "公園を遊び回る。", "Đi chơi khắp công viên."],
        [35, 1, "Động từ", "あたえる", "与える", "Dữ", "Trao tặng, gây ra (ảnh hưởng, thiệt hại)", ["影響を与える (Gây ra ảnh hưởng)", "チャンスを与える (Trao cơ hội)", "損害を与える (Gây thiệt hại)"], [{"word": "もたらす", "reading": "", "note": "Đem lại"}], [{"word": "奪う", "reading": "うばう", "meaning": "Cướp đoạt"}, {"word": "もらう", "reading": "", "meaning": "Nhận"}], "Rất hay đi với 影響を与える, 印象を与える, ダメージを与える.", "彼にプレゼントを与えました。", "Tôi đã tặng quà cho anh ấy."]
    ]
    return items
